AllCops:
  NewCops: enable
  Exclude:
    - config/**/*
    - bin/**/*
    - node_modules/**/*
    - vendor/**/*
    - server/**/*

Lint/MissingSuper:
  Exclude:
    - src/_components/**/*

Layout/LineLength:
  Max: 120

Lint/SuppressedException:
  Exclude:
    - Rakefile
