name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"

      - name: Install packages
        run: |
          yarn install --pure-lockfile
          sudo apt-get -yqq install libpq-dev

      - name: Build
        env:
          BRIDGETOWN_ENV: production
        run: |
          bin/bridgetown deploy

      - name: Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "output/*"
          target: /var/www/stefanvermaas.com/html/
          strip_components: 1
