name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP_ADDRESS }}:${{ secrets.DEPLOY_SSH_PORT }}/${{ secrets.DEPLOY_APP_NAME }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
